#
# This source file is part of the Stanford SpeziDevices open source project
#
# SPDX-FileCopyrightText: 2022 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  packageios:
    name: Build and Test Swift Package iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      scheme: SpeziDevices-Package
      resultBundle: SpeziDevices-iOS.xcresult
      artifactname: SpeziDevices-iOS.xcresult
  ios:
    name: Build and Test iOS
    uses: StanfordSpezi/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      path: 'Tests/UITests'
      scheme: TestApp
      resultBundle: TestApp-iOS.xcresult
      artifactname: TestApp-iOS.xcresult
  uploadcoveragereport:
    name: Upload Coverage Report
    needs: [packageios, ios]
    uses: StanfordBDHG/.github/.github/workflows/create-and-upload-coverage-report.yml@v2
    with:
      coveragereports: SpeziDevices-iOS.xcresult TestApp-iOS.xcresult
    secrets:
      token: ${{ secrets.CODECOV_TOKEN }}
